library(data.table)
library(lubridate)
library(dplyr)
fileName <- "household_power_consumption.txt"
colNames <- c("date","time","globalactivepower","globalreactivepower","voltage","globalintensity","submertering1","submertering2","submertering3")
householdPowerConsumption <- read.table(unz("household_power_consumption.zip","household_power_consumption.txt"), colClasses = c("character"),sep = ";", header = T)
#householdPowerConsumption <- data.table(householdPowerConsumption)
householdPowerConsumption <- householdPowerConsumption %>% filter(Date == "1/2/2007" | Date == "2/2/2007")
householdPowerConsumption[,10] <- dmy_hms(paste(householdPowerConsumption[,1],householdPowerConsumption[,2]))
householdPowerConsumption[,1] <- dmy(unlist(householdPowerConsumption[,1]))
householdPowerConsumption[,2] <- hms(unlist(householdPowerConsumption[,2]))
householdPowerConsumption[,3] <- as.numeric(unlist(householdPowerConsumption[,3]))
householdPowerConsumption[,4] <- as.numeric(unlist(householdPowerConsumption[,4]))
householdPowerConsumption[,5] <- as.numeric(unlist(householdPowerConsumption[,5]))
householdPowerConsumption[,6] <- as.numeric(unlist(householdPowerConsumption[,6]))
householdPowerConsumption[,7] <- as.numeric(unlist(householdPowerConsumption[,7]))
householdPowerConsumption[,8] <- as.numeric(unlist(householdPowerConsumption[,8]))
householdPowerConsumption[,9] <- as.numeric(unlist(householdPowerConsumption[,9]))
head(householdPowerConsumption)
str(householdPowerConsumption)
png("plot2.png", width = 480, height = 480)
with(householdPowerConsumption, plot(V10, Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = ""))
dev.off(which = dev.cur())
